### ISSUE TITLE
[Tweak] Remove Dylan Bartlett from Staff Showcase

### ISSUE THREAD

**Issue by nowmediaconnor** [nowmediaconnor/guten-csek#38]
## Description

Dylan no longer works at Csek so needs to be removed. This is mostly a content-side thing but since the Executive Team is well defined it's something that can be changed here.

## Expected Delivery

Included in the associated milestone.

**Comment by Alice-Vincent** [comment]
@nowmediaconnor Can you please replace Dylan with Kat, Creative Director? 

[https://csekcreative.wpengine.com/about-us/#close](url)

**Comment by nowmediaconnor** [comment]
@Alice-Vincent Can do! Could you email me a link to her portrait? I don't know where to find those in Drive

**Comment by Alice-Vincent** [comment]
Haha sorry, I copy-pasted the wrong link in the comment! Here it is: https://drive.google.com/file/d/15KfFPKQBhyzwRvO4JxyxCrp1RmVW_mx3/view?usp=share_link

**Comment by nowmediaconnor** [comment]
Haha, no prob!

Kat has been added

![Image](https://github.com/nowmediaconnor/guten-csek/assets/141870487/9b636310-34ce-4247-9fb2-b24da3128cd8)
