### ISSUE TITLE
[Tweak] Animate the team pictures on the home page (and remove Scott)

### ISSUE THREAD

**Issue by Alice-Vincent** [nowmediaconnor/guten-csek#67]

**Comment by nowmediaconnor** [comment]
@Alice-Vincent who should Scott be replaced by? Kat?

**Comment by nowmediaconnor** [comment]
Depends on #70

**Comment by nowmediaconnor** [comment]
Depends on #71

**Comment by Alice-Vincent** [comment]
I'd say Lauren https://drive.google.com/file/d/1h71whnnYi5uGDAdxMksczCWOcUCPhUx9/view?usp=sharing but not a bid deal
