### ISSUE TITLE
[Tweak] Modify View projects Button on Home page

### ISSUE THREAD

**Issue by Alice-Vincent** [nowmediaconnor/guten-csek#68]
Inspiration: https://preview.themeforest.net/item/salient-responsive-multipurpose-theme/full_screen_preview/4363266?_ga=2.113467911.1001349421.1699546835-638704889.1624270047

![Image](https://github.com/nowmediaconnor/guten-csek/assets/148800782/b8e07716-d298-45f3-a396-98f3128fa8c9)

**Comment by nowmediaconnor** [comment]
This is sweet! I love the frosted glass trend.

**Comment by nowmediaconnor** [comment]
Closed in #75
